[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase timeout for API routes (Pro plan allows up to 26 seconds)
  timeout = 26

# Environment variables for build
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# API route optimization
[[edge_functions]]
  function = "discovery-agent"
  path = "/api/agents/discovery" 